### ISSUE TITLE
Incomplete parameters.def file in PIPI-1.2.8 release

### ISSUE THREAD

**Issue by bugvid** [fcyu/PIPI#1]
The parameter file provided in the 1.2.8 release of PIPI is missing the following lines that are present in the source code version of the same file:

min_potential_charge = 2
max_potential_charge = 4

Here is the detailed error obtained running the software:
![issue_pipi-1 2 8_missing_parameter](https://cloud.githubusercontent.com/assets/26788746/24495695/58e5d2c4-1536-11e7-968a-217c876940f4.png)

Searching the source code reveals the error being due to missing parameters; adding them worked.
Not sure if the software is intended to work with default values if not provided, but in the current case it just throws back an exception related to the unfound values.

**Comment by fcyu** [comment]
Thanks for your report. The release has been updated.
