### ISSUE TITLE
Low robustness to the presence of unknown amino-acid in the protein sequence

### ISSUE THREAD

**Issue by bugvid** [fcyu/PIPI#2]
Proteins sequences present in Fasta files may include -not too rarely- undetermined amino-acids (often marked as * ).
It seems PIPI does not behave well when encountering a symbol in a protein sequence that is not described in its own internal amino-acid list, and crashes as reported below.

![issue_pipi-1 2 8_undetermined_amino_acid](https://cloud.githubusercontent.com/assets/26788746/24502844/cf2bcbaa-154f-11e7-9dc3-a8ba54173bee.png)

It would probably better if the software could just at least remove this specific protein from the database, warns the user, and pursue the rest of the processing.

**Comment by fcyu** [comment]
Thanks for your report. I will fix this bug in the next release. Right now, I suggest you to replace all "*" with a letter "X". Actually, PIPI regards "B", "J", "X", and "Z" as undetermined amino acids.

**Comment by bugvid** [comment]
Thanks for the suggestion, worked like a charm !

**Comment by fcyu** [comment]
Thanks. Actually, I've finished the next release. It improved a lot in terms of sensitivity and accuracy. I will release after through test.

**Comment by fcyu** [comment]
This has been fixed (Commit 58d6adf92e03f5398cf36503a1515d690074b86e) and included in the release 1.2.9.
