### ISSUE TITLE
Unimod.txt file in PIPI-1.2.8 release

### ISSUE THREAD

**Issue by bugvid** [fcyu/PIPI#3]
It seems a Post-Translational-Modification file is needed to run PIPI.

This file is however missing in PIPI-1.2.8 release -leading to PIPI crash-, and no mention is made of it or any instruction given in the Readme to build your own.

![issue_pipi-1 2 8_missing_unimod_file](https://cloud.githubusercontent.com/assets/26788746/24503121/05930798-1551-11e7-9af6-4fbddc078983.png)

The file can however be found in GitHub sources.

**Comment by fcyu** [comment]
Thanks for your report. The release has been updated.
